# Generated by Django 4.1 on 2023-08-12 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="fa_update_notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=20)),
                ("information", models.CharField(max_length=500)),
                ("date", models.DateField()),
                ("semester", models.CharField(default="", max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="faculty_info",
            fields=[
                (
                    "username",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=20)),
                ("Designation", models.CharField(default="", max_length=20)),
                ("name", models.CharField(default=" ", max_length=20)),
                ("email", models.EmailField(blank=True, max_length=20, unique=True)),
                ("user_type", models.CharField(default="1", max_length=20)),
                (
                    "profile_pic",
                    models.ImageField(blank=True, upload_to="profile_pics"),
                ),
                ("department", models.CharField(blank=True, max_length=70)),
                ("specialisation", models.CharField(default="None", max_length=70)),
                ("DOJ", models.DateField(blank=True, null=True)),
                ("years_of_experience", models.PositiveIntegerField(default=0)),
                ("bachelor_degree", models.CharField(default=None, max_length=50)),
                (
                    "bachelor_instituition",
                    models.CharField(default=None, max_length=50),
                ),
                ("bachelor_year", models.CharField(default=None, max_length=50)),
                ("Masters_degree", models.CharField(default=None, max_length=50)),
                ("Masters_instituition", models.CharField(default=None, max_length=50)),
                ("Masters_year", models.CharField(default=None, max_length=50)),
                ("Phd", models.CharField(default=None, max_length=50)),
                ("Phd_instituition", models.CharField(default=None, max_length=50)),
                ("Phd_year", models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="stu_complaints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("usn", models.CharField(default="", max_length=100)),
                ("faculty_name", models.CharField(default="", max_length=100)),
                ("department", models.CharField(default="", max_length=100)),
                ("complaint", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="students",
            fields=[
                (
                    "username",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("DOB", models.DateField()),
                ("email", models.EmailField(max_length=250, unique=True)),
                ("Name", models.CharField(max_length=250)),
                ("Branch", models.CharField(max_length=250, null=True)),
                ("semester", models.PositiveIntegerField()),
                (
                    "student_profile_pic",
                    models.ImageField(upload_to="stud_profile_pics"),
                ),
                ("user_type", models.CharField(blank=True, max_length=250)),
                (
                    "counsellor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="edu_app.faculty_info",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="student_marks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_1_code", models.CharField(default="None", max_length=10)),
                ("sub_1", models.PositiveIntegerField()),
                ("sub_2_code", models.CharField(default="None", max_length=10)),
                ("sub_2", models.PositiveIntegerField()),
                ("sub_3_code", models.CharField(default="None", max_length=10)),
                ("sub_3", models.PositiveIntegerField()),
                ("sub_4_code", models.CharField(default="None", max_length=10)),
                ("sub_4", models.PositiveIntegerField()),
                ("sub_5_code", models.CharField(default="None", max_length=10)),
                ("sub_5", models.PositiveIntegerField()),
                ("sub_6_code", models.CharField(default="None", max_length=10)),
                ("sub_6", models.PositiveIntegerField()),
                (
                    "usn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="edu_app.students",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="student_attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_1_code", models.CharField(default="None", max_length=10)),
                ("sub_1_atn", models.PositiveIntegerField()),
                ("sub_2_code", models.CharField(default="None", max_length=10)),
                ("sub_2_atn", models.PositiveIntegerField()),
                ("sub_3_code", models.CharField(default="None", max_length=10)),
                ("sub_3_atn", models.PositiveIntegerField()),
                ("sub_4_code", models.CharField(default="None", max_length=10)),
                ("sub_4_atn", models.PositiveIntegerField()),
                ("sub_5_code", models.CharField(default="None", max_length=10)),
                ("sub_5_atn", models.PositiveIntegerField()),
                ("sub_6_code", models.CharField(default="None", max_length=10)),
                ("sub_6_atn", models.PositiveIntegerField()),
                (
                    "usn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="edu_app.students",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stu_Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("is_present", models.BooleanField(default=False)),
                (
                    "student_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="edu_app.students",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="detailed_cie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.PositiveIntegerField(default="")),
                ("branch", models.CharField(default="", max_length=100)),
                ("subject_code", models.CharField(default="", max_length=10)),
                ("IA1", models.PositiveIntegerField(default=0)),
                ("IA2", models.PositiveIntegerField(default=0)),
                ("IA3", models.PositiveIntegerField(default=0)),
                ("A1", models.PositiveIntegerField(default=0)),
                ("A2", models.PositiveIntegerField(default=0)),
                (
                    "usn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="edu_app.students",
                    ),
                ),
            ],
        ),
    ]
