# Generated by Django 4.1 on 2023-08-12 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("edu_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="detailed_cie", name="usn",),
        migrations.AddField(
            model_name="detailed_cie",
            name="username",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="edu_app.students",
            ),
        ),
    ]
