# Generated by Django 4.1 on 2023-08-12 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("edu_app", "0002_remove_detailed_cie_usn_detailed_cie_username"),
    ]

    operations = [
        migrations.RemoveField(model_name="detailed_cie", name="username",),
        migrations.AddField(
            model_name="detailed_cie",
            name="usn",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="edu_app.students",
            ),
        ),
    ]
