# Generated by Django 4.1 on 2023-08-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu_app", "0003_remove_detailed_cie_username_detailed_cie_usn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detailed_cie",
            name="usn",
            field=models.CharField(default="", max_length=20),
        ),
    ]
