# Generated by Django 4.1 on 2023-08-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu_app", "0004_alter_detailed_cie_usn"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailed_cie",
            name="finalise",
            field=models.CharField(default="NULL", max_length=10),
        ),
    ]
