# Generated by Django 4.1 on 2023-08-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu_app", "0007_detailed_cie_total"),
    ]

    operations = [
        migrations.DeleteModel(name="detailed_cie",),
        migrations.AddField(
            model_name="student_marks",
            name="branch",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="student_marks",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="student_marks",
            name="semester",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="student_marks",
            name="usn",
            field=models.CharField(default="", max_length=20),
        ),
    ]
