# Generated by Django 4.1 on 2023-08-13 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edu_app", "0008_delete_detailed_cie_student_marks_branch_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="student_marks", name="name",),
    ]
