# Generated by Django 4.1 on 2023-08-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu_app", "0009_remove_student_marks_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("particulars", models.CharField(max_length=100)),
                ("amount", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(name="student_attendance",),
    ]
