# Generated by Django 4.1 on 2023-08-16 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("edu_app", "0010_payments_delete_student_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="usn",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="edu_app.students",
            ),
        ),
    ]
