# Generated by Django 4.1 on 2023-08-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu_app", "0011_payments_usn"),
    ]

    operations = [
        migrations.RemoveField(model_name="stu_attendance", name="is_present",),
        migrations.RemoveField(model_name="stu_attendance", name="student_name",),
        migrations.AddField(
            model_name="stu_attendance",
            name="Branch",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="stu_attendance",
            name="ending_time",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="stu_attendance",
            name="semester",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stu_attendance",
            name="starting_time",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="stu_attendance",
            name="subject_code",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="stu_attendance",
            name="usn",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="stu_attendance",
            name="date",
            field=models.TextField(default=""),
        ),
    ]
